theme: jekyll-theme-slate
title: Developed by Neato
description: New & Improved BmLauncher Replacement
show_downloads: true
github:
  zip_url: https://github.com/neatodev/BmLauncher/releases/latest
favicon: true
